### ISSUE TITLE
Please add 16bit-per-channel support

### ISSUE THREAD

**Issue by Videogamer555** [danielmarschall/filter_foundry#1]
I need to process a 16bit image with a custom filter. I found filter factory very useful for 8bit image processing when needing a custom filter. However that's very limited. I have 16bit images that need processing using a custom filter that isn't available in the normal set of Photoshop filters that come with the software.

**Comment by danielmarschall** [comment]
Thank you for the suggestion! I will work on this the next days. Release will be very soon.

**Comment by danielmarschall** [comment]
Worked a few hours on this today.

Besides a bunch of tests, there are 2 open problems.

1. Preview is messed up and I am not sure why
2. At PiPL, Photoshop seems to ignore `enbl` and wants `mode` instead. And I am not sure which values to set there.

I hope to have these issues fixed for the next release which hopefully gets released by the end of the year.

**_Work-In-Progress patch:_**

```diff
Index: ff.h
===================================================================
--- ff.h	(revision 577)
+++ ff.h	(working copy)
@@ -113,6 +113,9 @@
 
 extern int tokpos,tokstart,varused[];
 extern TCHAR *errstr;
+extern int bytesPerPixel;
+extern value_type maxChannelValue;
+extern int valueFactor;
 
 #define LOADING_OK 0
 /**
@@ -175,7 +178,7 @@
 // from process.c:
 
 Boolean setup(FilterRecordPtr pb);
-void evalpixel(unsigned char *outp,unsigned char *inp);
+void evalpixel(unsigned char *outp,unsigned char *inp, int valueFactor);
 
 // from make.c:
 
Index: main.c
===================================================================
--- main.c	(revision 577)
+++ main.c	(working copy)
@@ -500,7 +500,7 @@
 		}
 	}
 	if (resetFormulas) {
-		if (gpb->imageMode == plugInModeRGBColor) {
+		if ((gpb->imageMode == plugInModeRGBColor) || (gpb->imageMode == plugInModeRGB48) || (gpb->imageMode == plugInModeRGB96)) {
 			strcpy(gdata->parm.szFormula[0], "r");
 			strcpy(gdata->parm.szFormula[1], "g");
 			strcpy(gdata->parm.szFormula[2], "b");
Index: PiPL_body.rc
===================================================================
--- PiPL_body.rc	(revision 577)
+++ PiPL_body.rc	(working copy)
@@ -34,17 +34,8 @@
 VENDORID, LC(p,r,t,y), NULLID, 4L, NULLID,
 
 /* Supported modes */
-VENDORID, LC(m,o,d,e), NULLID, 4L, /* First byte:     */ /*doesSupportBitmap|*/
-                                                         doesSupportGrayScale|
-                                                         /*doesSupportIndexedColor|*/
-                                                         doesSupportRGBColor|
-                                                         doesSupportCMYKColor|
-                                                         doesSupportHSLColor|
-                                                         doesSupportHSBColor|
-                                                         doesSupportMultichannel|
-                                   /* Second byte: */    doesSupportDuotone|
-                                                         doesSupportLABColor,
-                                   /* 3rd & 4th byte: */ 0,
+/* TODO: which modes need to be applied to support 16 bits? The SDK does not contain things like doesSupportGray16. For some reason, we DO NEED 'mode', because 'enbl' does not work??? */
+VENDORID, LC(m,o,d,e), NULLID, 4L, 65535, 0,
 
 /* We need this to enable the plugin for BigDocuments */
 VENDORID, LC(m,s,3,2), NULLID, 8L, 2000000L, 2000000L,
@@ -60,7 +51,8 @@
 /* Enable info */
 /* Note: Length 116 must be divisible by 4 */
 /* "Plug-in Resource Guide.pdf", pages 61-62 */
-VENDORID, LC(e,n,b,l), NULLID, 116L, "in (PSHOP_ImageMode, GrayScaleMode, RGBMode, CMYKMode, HSLMode, HSBMode, MultichannelMode, DuotoneMode, LabMode)\0\0\0\0",
+/* TODO: check if this is all correct... for some reason 'enbl' does not seem to be used */
+VENDORID, LC(e,n,b,e), NULLID, 188L, "in (PSHOP_ImageMode, GrayScaleMode, RGBMode, CMYKMode, HSLMode, HSBMode, MultichannelMode, DuotoneMode, LabMode, RGB48Mode, Gray16Mode) ||PSHOP_ImageDepth == 16||PSHOP_ImageDepth == 32\0\0\0\0",
 
 /* MonitorScalingAware */
 /* TODO: Do we support it? For now, commented out */
Index: preview.c
===================================================================
--- preview.c	(revision 577)
+++ preview.c	(working copy)
@@ -520,6 +520,7 @@
 			gpb->propertyProcs->setPropertyProc(kPhotoshopSignature,propWatchSuspension,0,watchsusp+1,NULL);
 		}
 
+		// TODO: on 16bit, garbage is shown in the preview. what's the reason? needs to preview be 8bit?
 		e = gpb->displayPixels(&preview_pmap,&srcRect,imagebounds.top,imagebounds.left,hdc);
 
 		if((gpb->propertyProcs != NULL) && gpb->propertyProcs->getPropertyProc)
Index: process.c
===================================================================
--- process.c	(revision 577)
+++ process.c	(working copy)
@@ -29,6 +29,10 @@
 extern int nplanes,varused[],cnvused;
 extern struct node *tree[];
 
+int bytesPerPixel;
+value_type maxChannelValue;
+int valueFactor; // for higher bit deapth, things like 'd' and 'm' should have a higher magnitude
+
 /**
 points to first row, first column of selection image data
 this is used by src() and cnv() functions to access pixels
@@ -62,6 +66,39 @@
 	int srcrad;
 	int i;
 
+	switch (pb->depth) {
+	case 0:
+		// Photoshop <4.0 does not support this property. Use 8 bits
+		bytesPerPixel = 1;
+		maxChannelValue = 255;
+		valueFactor = 1;
+		break;
+	case 1:
+		// 1 bit (not supported?)
+		bytesPerPixel = 1; // TODO: is this correct for 1bit mode???
+		maxChannelValue = 1; // TODO: is this correct for 1bit mode???
+		valueFactor = 1;
+		break;
+	case 8:
+		// 8 bits
+		bytesPerPixel = 1;
+		maxChannelValue = 255;
+		valueFactor = 1;
+		break;
+	case 16:
+		// 16 bits
+		bytesPerPixel = 2;
+		maxChannelValue = 32768; // sic: Photoshop says 0..32768 in the "Info" panel. Not 32767
+		valueFactor = 128;
+		break;
+	case 32:
+		// 32 bits (not supported)
+		bytesPerPixel = 4;
+		maxChannelValue = 65535; // TODO: ??? Photoshop says 0-1, so this seems to be some kind of float... we probably cannot use that in FilterFoundry
+		valueFactor = 129;
+		break;
+	}
+
 	// Attention: If you introduce new variables, please define them also in lexer.l
 	if (HAS_BIG_DOC(pb)) {
 		var['X'] = BIGDOC_FILTER_RECT(pb).right - BIGDOC_FILTER_RECT(pb).left;
@@ -74,7 +111,7 @@
 	var['D'] = val_D;
 	var['M'] = ff_M();
 
-	var['R'] = var['G'] = var['B'] = var['A'] = var['C'] = 255;
+	var['R'] = var['G'] = var['B'] = var['A'] = var['C'] = maxChannelValue;
 	var['I'] = val_I;
 	var['U'] = val_U;
 	var['V'] = val_V;
@@ -121,41 +158,62 @@
 	return i==nplanes; /* all required expressions parse OK */
 }
 
-void evalpixel(unsigned char *outp,unsigned char *inp){
+void evalpixel(unsigned char *outp,unsigned char *inp,int valueFactor){
 	int f,k;
 
 	if(needinput){
-		var['r'] = inp[0];
-		var['g'] = nplanes > 1 ? inp[1] : 0;
-		var['b'] = nplanes > 2 ? inp[2] : 0;
-		var['a'] = nplanes > 3 ? inp[3] : 0;
+		if (bytesPerPixel == 1) {
+			var['r'] = inp[0];
+			var['g'] = nplanes > 1 ? inp[1] : 0;
+			var['b'] = nplanes > 2 ? inp[2] : 0;
+			var['a'] = nplanes > 3 ? inp[3] : 0;
+		} else if (bytesPerPixel == 2) {
+			var['r'] = (nplanes > 0) ? ((uint16_t)(uint8_t)inp[0] | (uint8_t)inp[1] << 8) : 0;
+			var['g'] = (nplanes > 1) ? ((uint16_t)(uint8_t)inp[2] | (uint8_t)inp[3] << 8) : 0;
+			var['b'] = (nplanes > 2) ? ((uint16_t)(uint8_t)inp[4] | (uint8_t)inp[5] << 8) : 0;
+			var['a'] = (nplanes > 3) ? ((uint16_t)(uint8_t)inp[6] | (uint8_t)inp[7] << 8) : 0;
+		}
 
 		// For Y, the definition is Y := 0.299R + 0.587G + 0.114B
-		if(varused['i']) var['i'] = ff_i();
+		if(varused['i']) var['i'] = ff_i() * valueFactor;
 
 		// For U, the definition is U := (B-Y) * 0.493; the range would be [-111..111]
 		// Filter Factory divided it by 2, resulting in a range of [-55..55].
 		// Due to compatibility reasons, we adopt that behavior.
-		if(varused['u']) var['u'] = ff_u();
+		if(varused['u']) var['u'] = ff_u() * valueFactor;
 
 		// For V, the definition is V := (R-Y) * 0.877; the range would be [-156..156]
 		// Filter Factory divided it by 2, resulting in a range of [-78..78].
 		// Due to compatibility reasons, we adopt that behavior.
-		if(varused['v']) var['v'] = ff_v();
+		if(varused['v']) var['v'] = ff_v() * valueFactor;
 	}
 
-	if(varused['d']) var['d'] = ff_d();
-	if(varused['m']) var['m'] = ff_m();
+	if(varused['d']) var['d'] = ff_d() * valueFactor;
+	if(varused['m']) var['m'] = ff_m() * valueFactor;
 
-	for(k = 0; k < nplanes; ++k){
-		if(needinput)
-			var['c'] = inp[k];
-		var['z'] = k;
-		var['p'] = k; // undocumented alias of z
-		f = eval(tree[k]);
-		if (outp)
-			outp[k] = f<0 ? 0 : (f>255 ? 255 : f); // clamp channel value to 0-255
+	if (bytesPerPixel == 1) {
+		for (k = 0; k < nplanes; ++k) {
+			if (needinput)
+				var['c'] = inp[k];
+			var['z'] = k;
+			var['p'] = k; // undocumented alias of z
+			f = eval(tree[k]);
+			if (outp)
+				outp[k] = f < 0 ? 0 : (f > maxChannelValue ? maxChannelValue : f); // clamp channel value
+		}
 	}
+	else if (bytesPerPixel == 2) {
+		for (k = 0; k < nplanes; ++k) {
+			if (needinput)
+				var['c'] = (nplanes > 0) ? ((uint16_t)(uint8_t)inp[k * 2] | (uint8_t)inp[k * 2 + 1] << 8) : 0;
+			var['z'] = k;
+			var['p'] = k; // undocumented alias of z
+			f = eval(tree[k]);
+			if (outp) {
+				*((uint16_t*)(outp + k * 2)) = f < 0 ? 0 : (f > maxChannelValue ? maxChannelValue : f); // clamp channel value
+			}
+		}
+	}
 }
 
 //#define PROCESS_SCALED_GAP_DEBUG 1
@@ -179,7 +237,7 @@
 OSErr process_scaled_bigdoc(FilterRecordPtr pb, Boolean progress,
 			  VRect filterPiece, VRect outPiece,
 			  void *outData, long outRowBytes, double zoom){
-	unsigned char *inrow,*outrow,*outp;
+	char*inrow,*outrow,*outp;
 	int j,i;
 	int64_t t, ticks = TICKCOUNT();
 	double x,y,k;
@@ -210,7 +268,7 @@
 	// find base pointer to selection image data
 	image_ptr = (unsigned char*)pb->inData
 				+ (long)pb->inRowBytes*(filterRect.top - inRect.top)
-				+ (long)nplanes*(filterRect.left - inRect.left);
+				+ (long)nplanes*(filterRect.left - inRect.left) * bytesPerPixel;
 
 	if (state_changing_funcs_used) {
 		// Fill gap between selection/filter top border and top preview zoomed border
@@ -232,7 +290,7 @@
 				#endif
 
 				var['x'] = (value_type)x;
-				evalpixel(NULL,inrow + (long)(x)*nplanes);
+				evalpixel(NULL,inrow + (long)(x)*nplanes * bytesPerPixel, valueFactor);
 			}
 
 			#ifdef PROCESS_SCALED_GAP_DEBUG
@@ -264,13 +322,13 @@
 				#endif
 
 				var['x'] = (value_type)x;
-				evalpixel(NULL,inrow + (long)(x)*nplanes);
+				evalpixel(NULL,inrow + (long)(x)*nplanes * bytesPerPixel, valueFactor);
 			}
 		}
 
 		// i indexes scaled output columns
 		for( outp = outrow, i = outPiece.left, x = (double)filterPiece.left - (double)filterRect.left ;
-			 i < outPiece.right ; ++i, outp += nplanes, x += zoom )
+			 i < outPiece.right ; ++i, outp += nplanes*bytesPerPixel, x += zoom )
 		{
 			#ifdef PROCESS_SCALED_GAP_DEBUG
 			if (state_changing_funcs_used && last_good_x != (int)floor(x-1)) { sprintf(s, "Non calculated X gap, type 2b: %f, last good %d, zoom %f\n", x, last_good_x, zoom); simplealert(s); } last_good_x = (int)floor(x);
@@ -277,7 +335,7 @@
 			#endif
 
 			var['x'] = (value_type)x;  // index of corresponding *input* column, left of selection == 0
-			evalpixel(outp,inrow + (long)(x)*nplanes); /* var['x'] & var['y'] are implicit parameters */
+			evalpixel(outp,inrow + (long)(x)*nplanes * bytesPerPixel, valueFactor); /* var['x'] & var['y'] are implicit parameters */
 
 			if (state_changing_funcs_used) {
 				// Fill gap between each X-preview-pixel (discarded pixels due to zoom level)
@@ -288,7 +346,7 @@
 
 					var['x'] = (value_type)k;
 					if (var['x'] >= var['X']) break;
-					evalpixel(NULL,inrow + (long)(k)*nplanes);
+					evalpixel(NULL,inrow + (long)(k)*nplanes * bytesPerPixel, valueFactor);
 				}
 			}
 		}
@@ -302,7 +360,7 @@
 				#endif
 
 				var['x'] = (value_type)x;
-				evalpixel(NULL,inrow + (long)(x)*nplanes);
+				evalpixel(NULL,inrow + (long)(x)*nplanes * bytesPerPixel, valueFactor);
 			}
 
 			#ifdef PROCESS_SCALED_GAP_DEBUG
@@ -330,7 +388,7 @@
 					#endif
 
 					var['x'] = (value_type)x;
-					evalpixel(NULL,inrow + (long)(x)*nplanes);
+					evalpixel(NULL,inrow + (long)(x)*nplanes * bytesPerPixel, valueFactor);
 				}
 
 				#ifdef PROCESS_SCALED_GAP_DEBUG
Index: ui.c
===================================================================
--- ui.c	(revision 577)
+++ ui.c	(working copy)
@@ -232,13 +232,29 @@
 /**
 one-time initialisation of dialog box
 */
-void maindlginit(DIALOGREF dp){
+void maindlginit(DIALOGREF dp) {
 	char s[0x100];
 	int i;
-	const char *channelsuffixes[] = {
-		"", "KA", "I", "RGBA",
-		"CMYK", "HSL", "HSB", "1234",
-		"DA", "LabA"
+	const char* channelsuffixes[] = {
+		// ImagesMode according to PIGeneral.h
+		"",     // plugInModeBitmap
+		"KA",   // plugInModeGrayScale
+		"I",    // plugInModeIndexedColor
+		"RGBA", // plugInModeRGBColor
+		"CMYK", // plugInModeCMYKColor (unfortunately without transparency)
+		"HSL",  // plugInModeHSLColor
+		"HSB",  // plugInModeHSBColor
+		"1234", // plugInModeMultichannel
+		"DA",   // plugInModeDuotone
+		"LabA", // plugInModeLabColor
+		"KA",   // plugInModeGray16
+		"RGBA", // plugInModeRGB48
+		"LabA", // plugInModeLab48
+		"CMYK", // plugInModeCMYK64 (unfortunately without transparency)
+		"1234", // plugInModeDeepMultichannel
+		"DA",   // plugInModeDuotone16
+		"RGBA", // plugInModeRGB96
+		"KA"    // plugInModeGray32
 	};
 
 	/* hide unused expression items */
```

**Comment by danielmarschall** [comment]
Day 2 of development done. The preview now works as well as other bugs fixed. Goal is very close.

**Comment by danielmarschall** [comment]
@Videogamer555 I think I have a prototype which now works will all existing color modes in 8, 16, and 32 bit.
Do you want to beta test it, or wait for the official release?

**Comment by Videogamer555** [comment]
16bit grayscale and 16bit RGB are the only color spaces I need right now.

Also the ranges in 16bit mode should theoretically be between 0 and 65535.
Actually it's a bit more complicated than that. If I remember correctly,
Photoshop actually doesn't use every possible value between 0 and 0xFFFF.
It uses a method which I've heard others call "15bits+1" where the highest
possible value is actually 0x8000 (not 0xFFFF). While this does still
require 16 bits of bit-space to work, it doesn't use any values between
0x8001 and 0xFFFF. This is because if all possible values were used, there
would be 65536 total values, where the highest value is 65535 (an odd
number). There's no way to split this with an integer midpoint in the
middle of the value range for symmetrical signed operations (where the
midpoint needs to be subtracted before the operation is performed and added
back again after the operation is performed), as a midpoint of a value
range starting at zero is always the maximum possible value for that range
divided by 2, and dividing any odd number by 2 gives you a non-integer
result.

This is one of the problems with 8bit mode. The midpoint between 0 and 255
is 127.5 (255 / 2 = 127.5), which is not an integer. So for operations that
worked with signed numbers, by first subtracting the midpoint from the
pixel value, you end up subtracting either 127 or 128 (only an
approximation of the midpoint), before doing the operation, and then adding
that offset back again after the operation. And this makes the operation
asymmetrical. So when Photoshop uses 16bit mode. it makes sure to use an
odd number of values, so that the maximum possible value is an even number
(number of possible values - 1 = maximum possible value), to guarantee that
there is an integer midpoint available. Thus there's actually only 0x8001
possible pixel values in 16bit mode, ranging from 0 to 0x8000. The midpoint
is at exactly 0x4000, which is an integer.

So if you decide to implement 16bit mode, realize that the only valid
values are between 0x0000 and 0x8000. My own research shows that it may be
a bit more complicated than that though. I don't know how it internally
handles this 15bits+1 mode (you may have some insight into how this works,
as you actually write plugins), but externally, when saving a file and
choosing *.raw to save the raw headerless output to a file, it's not as
simple as the values being between 0x0000 and 0x8000. It makes sure to
spread the values across the complete range of 0x0000 to 0xFFFF, while
skipping every other value. While doing my own research/experiments on how
it saves the values to a 16bit raw file, I have found that in the first
half of the 16bit range (between 0x0000 and 0x8000) it skips odd numbered
values (the first 3 valid output values are 0x0000, 0x0002, and 0x0004). In
the second half of the range (between 0x8001 and 0xFFFF) it skips the even
numbered values (the last 3 valid output values are 0xFFFB, 0xFFFD,
0xFFFF). Right around the midpoint where it switches these skipping
methods, the values are 0x7FFC, 0x7FFE, 0x8000, 0x8001, and 0x8003. So it
makes sure to include the value 0x8000 (the start of the upper range) even
though it's an even number, and in the upper range the even numbers get
skipped. The switchover point to skipping even numbers is just after 0x8000.

Now it's entirely possible that this scattering of the values in saved
output is just done to make sure that if another program opens it, it will
look visually correct (opening a file with a maximum value of 0x8001 will
appear to be half brightness, but if it spans the full range it will look
correct), while internally Photoshop may actually actually using the exact
range of 0x0000 to 0x8001. I don't know that because writing my own code
using the Photoshop SDK for plugins like that is beyond my ability right
now. However these are some points for you to consider if you decide to add
16bit support to your Filter Foundry plugin.

**Comment by danielmarschall** [comment]
@Videogamer555 Don't worry, I've already figured that out. But I am glad that you solved the mystery why it is 32768 and not 32767, because it has a integer midpoint.

I support both 16-bit (range 0x0000 - 0x8000) and 32-bit (floating point, although it is internally calculated as 23 bit, because Filter Foundry needs to work with integers), with all possible color modes. I could give you a preview version if you like

**Comment by Videogamer555** [comment]
Thanks. It would be nice if you could send me a preview version that does
support Photoshop's 16bit RGB and Grayscale modes.

**Comment by danielmarschall** [comment]
@Videogamer555 

I have released the new version here: https://github.com/danielmarschall/filter_foundry/releases/tag/1.7.0.22

I have done a lot of tests and did not find any problems. I would be very happy if you could test it too.

Regarding 16-bit and 32-bit color spaces, please carefully read the documentation, where I describe how they are handled.

(In short, you have do replace things like `d` with `d*(C/255)` so that the 16/32-bit result looks similar to the 8-bit result)

**Comment by Videogamer555** [comment]
> @Videogamer555
> 
> I have released the new version here: https://github.com/danielmarschall/filter_foundry/releases/tag/1.7.0.22
> 
> I have done a lot of tests and did not find any problems. I would be very happy if you could test it too.
> 
> Regarding 16-bit and 32-bit color spaces, please carefully read the documentation, where I describe how they are handled.
> 
> (In short, you have do replace things like `d` with `d*(C/255)` so that the 16/32-bit result looks similar to the 8-bit result)

Thanks for that. I was just reading the PDF manual for it, and I noticed something that seems unusual. I'm not sure if it's a typo, but I notice for the "a" and "b" channels of Lab color, when in 16bit mode, it says the range of values is from -16384 to 16383. While the lower number is correct, the upper number looks wrong. It doesn't make sense, because the 15bits+1 range used by Photoshop's "16 bits" mode actually would allow for the maximum value to be 16384 not 16383, when operating in a signed number mode (such as the "a" or "b" channel of Lab color space). That was actually the reason that 15bits+1 is used, is to make sure there's an integer midpoint, so that there are an equal number of available values above and below that midpoint. If your documentation is correct that the upper value here is 16383, while the lower value is -16384, then that means there are NOT an equal number of values above and below the midpoint. Are you sure your documentation is correct where it says that the range here is actually only -16384 to 16383?

**Comment by Videogamer555** [comment]
I just discovered a bug. The src(x,y,channel_number) function doesn't work correctly when in 16bit mode. It still works correctly when in 8bit mode, but not in 16bit mode. My version of Photoshop isn't new enough to have 32bit mode, so I can't test 32bit mode though so I can't tell you if the src function works correctly in 32bit mode.

**Comment by danielmarschall** [comment]
Thank you for that hint! This sounds logical, but of course I want to verify that this is the case.

I have the problem that I am unable to produce such a color in Photoshop. Using the default color picker I only get color "#ff4300" which has the a*/b* value 16256. I did not manage to produce the color with a*/b* 16383 or higher. Do you have an idea how I can verify Photoshop's maximum value?

**Comment by danielmarschall** [comment]
To your second point, thank you for the bug report! I can verify that `src()`,  `rad()`,  and `cnv()` are broken for 16/32 bit. I will work on it now.

**Comment by danielmarschall** [comment]
Attached ( [prototype.zip](https://github.com/user-attachments/files/17708510/prototype.zip) ) you will find a prototype that fixes:
- src/rad/cnv bug (please verify that it works now)
- Upper range of Lab range changed to 16384

**_Thank you so much for your feedback and help!!!
For this prototype, please save your work a bit more often, just in case something crashes._**

---

About the Lab color, I believe the upper limit is 16256, which sounds very weird...!

I created the following filter:

```
r = 32768
g = 16384
b = 16384
a = a
```

The plugin then wrote this data into memory (as I have increased the limit from 16383 to 16384)

The resulting image gave an image with the Lab values:

![image](https://github.com/user-attachments/assets/99739174-e04b-4da7-bafd-35753c2a89bb)

... If you come to the same conclusion that 16256 is the upper limit, then I will change the documentation and change the limit in the code again.


Edit: Googling "16256 16384 photoshop lab" shows that other users have the same experience... so yes, 16256 seems to be the limit

**Comment by Videogamer555** [comment]
> Attached ( [prototype.zip](https://github.com/user-attachments/files/17708510/prototype.zip) ) you will find a prototype that fixes:
> 
>     * src/rad/cnv bug (please verify that it works now)
> 
>     * Upper range of Lab range changed to 16384
> 
> 
> **_Thank you so much for your feedback and help!!! For this prototype, please save your work a bit more often, just in case something crashes._**
> 
> About the Lab color, I believe the upper limit is 16256, which sounds very weird...!
> 
> I created the following filter:
> 
> ```
> r = 32768
> g = 16384
> b = 16384
> a = a
> ```
> 
> The plugin then wrote this data into memory (as I have increased the limit from 16383 to 16384)
> 
> The resulting image gave an image with the Lab values:
> 
> ![image](https://private-user-images.githubusercontent.com/28412477/385072095-99739174-e04b-4da7-bafd-35753c2a89bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzOTc0MTksIm5iZiI6MTczMTM5NzExOSwicGF0aCI6Ii8yODQxMjQ3Ny8zODUwNzIwOTUtOTk3MzkxNzQtZTA0Yi00ZGE3LWJhZmQtMzU3NTNjMmE4OWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA3MzgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMGVjMzg2ZWM1ZTI3ZDVkY2ZhOWE5MDJkYWQwYjhmMTg1NmY4ODIxZDM0NzJmZjVlNDY3MTY0ODc4MzQ1N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RunIPduGqf--XQyAwM9teOVhaA8g0yNzUaH1O5M1Xo4)
> 
> ... If you come to the same conclusion that 16256 is the upper limit, then I will change the documentation and change the limit in the code again.
> 
> Edit: Googling "16256 16384 photoshop lab" shows that other users have the same experience... so yes, 16256 seems to be the limit

The src function now actually causes Photoshop to crash when working on 16bit RGB pictures. The moment you type the closing ")" to complete the function it crashes. It works fine for 8bit RGB pictures though. So I tried a work around, I configured the filter in 8bit mode, and then changed the picture to 16bit, and then did Ctrl+F to reuse the same filter (but without opening the Filter Foundry dialog box), and now it didn't crash the program, but it did pop up an error message box that said "Could not complete the Filter Foundry command because of a program error.". I've attached a screenshot of that message box to this post.
![image](https://github.com/user-attachments/assets/4e635cd0-d59a-4760-8681-eba1ca17b368)

**Comment by Videogamer555** [comment]
Another test. I tried again but this times in 16bit Grayscale. This time it didn't crash but it did show something was very wrong. I did src(x,y,0) and the preview didn't look right immediately. So I clicked ok to see what it would actually output to the picture, and sure enough the output to the picture was also glitched. It should have been all white (the source image was plain white) but instead it shows something that looks like it's data from a non-image part of memory. It seems like the problem may be that the src function is reading memory that's outside of the memory allocated for the image data. I've attached a screenshot of this to this post, and that in some cases it attempts to read memory that's not even allocated (the address of at least one of the pixels it attempts to read is in non-allocated memory space) which leads to an immediate software crash.
![image](https://github.com/user-attachments/assets/3aa4a4a0-e09c-43aa-bd58-5de35b9cea45)

**Comment by Videogamer555** [comment]
Ok, so finally I attached a debugger (I used OllyDbg) to the Photoshop process and attempted to use the Filter Foundry plugin with src(x,y,z) and immediately the debugger stopped the execution with the error "Access violation when reading [3FAA6208]". I've attached a screenshot of the debugger this post.
![image](https://github.com/user-attachments/assets/7aa69571-0fa5-4416-a9c1-86252ad072ea)

Note that it refers to the module name as FilterFoundry_prototype_8bf because I renamed the plugin to FIlterFoundry_prototype.8bf so I wouldn't confuse it with the stable version (and likewise renamed the stable version to FilterFoundry.8bf.old so that Photoshop won't try to load it, as they both have the same internal name and would conflict if both were to be loaded).

**Comment by danielmarschall** [comment]
Thank you so much for your feedback!
Attached you will find another prototype, this time src() as well as cnv() should be fine!
[prototype2.zip](https://github.com/user-attachments/files/17716499/prototype2.zip)

**Comment by danielmarschall** [comment]
Version 1.7.0.23 has been released (it is identical to the prototype 2)
If you find anything else, please write me. I am very happy that you are using Filter Foundry and giving suggestions and feedback

**Comment by Videogamer555** [comment]
> Version 1.7.0.23 has been released (it is identical to the prototype 2) If you find anything else, please write me. I am very happy that you are using Filter Foundry and giving suggestions and feedback

Ok so the src function works now. I noticed that the ~ operator (bitwise Not operator) isn't working. I haven't used it before really, so I don't know when it broke, but it doesn't work now. The output of using this operator is always 0 (zero). When I do ~0 it (meaning Not 0, meaning all bits in the 8bit byte or 16bit word should be 1), it should show up as a color of maximum intensity (maximum red if used in the red channel), but instead it just gives me black in all situations. In fact, there's no value that I can feed to the ~ operator that will give me a non-zero output. This tells me that the ~ operator is just completely broken. This problem exists in both RGB and Grayscale modes, as well as in both 8bit and 16bit bitdepths.

**Comment by danielmarschall** [comment]
Thanks for testing the functionality!

Actually, I also have never worked with the `~` operator.

According to ChatGPT, all bits get flipped, including the negative bit, so `~5` comes `-6`. You have seen 0, because negative numbers are set to 0 (except for Lab a* and b*).

I tested it with Filter Factory and Filter Foundry, both get the same results:

`~128 + 130 == 1`

So everything is good

**Comment by danielmarschall** [comment]
I will close this issue now, since the feature is implemented.
If you have any other ideas and wishes, or bugreports, please don't hesitate to contact me !
